# Generated by Django 4.2.21 on 2025-06-06 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_patient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
