# Generated by Django 4.2.23 on 2025-06-16 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_patient'),
        ('ai_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DicomFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='dicoms/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dicom_files', to='auth_app.patient')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed_image', models.ImageField(upload_to='processed_images/')),
                ('slice_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_dicom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_app.dicomfile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_images', to='auth_app.patient')),
            ],
            options={
                'ordering': ['slice_number'],
            },
        ),
    ]
