# Generated by Django 4.2.23 on 2025-06-19 10:59

import ai_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0002_dicomfile_processedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedimage',
            name='processed_image',
            field=models.ImageField(upload_to=ai_app.models.processed_image_upload_to),
        ),
    ]
