# Generated by Django 4.2.23 on 2025-06-21 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0003_alter_processedimage_processed_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='patient_id',
            new_name='dossier_id',
        ),
    ]
